name: Build Docker image
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Проверяем, что Dockerfile существует
      - name: Check if Dockerfile exists
        id: check_dockerfile
        run: |
          if [ -f Dockerfile ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      # 3️⃣ Собираем Docker-образ только если файл найден
      - name: Build Docker image
        if: steps.check_dockerfile.outputs.found == 'true'
        run: |
          echo "Dockerfile found — building image..."
          docker build -t my-app:latest .
      
      # 4️⃣ (опционально) если файла нет — выводим сообщение
      - name: Skip build
        if: steps.check_dockerfile.outputs.found == 'false'
        run: echo "No Dockerfile found. Skipping build."
